<<<<<<< HEAD
import React from "react";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from '../components/Footer';
import NavbarComponent from "@/components/NavbarComponent";
import {Providers} from "./providers";
>>>>>>> 0267a0a04f0d654ee9a4234823d205c90bde2816

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Gymkhana Website',
  description: 'New Gymkhana Website',
}
=======
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> 0267a0a04f0d654ee9a4234823d205c90bde2816

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<<<<<<< HEAD
    <html lang="en" className="smooth-scroll">
      <body className={inter.className}>{children}</body>
=======
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavbarComponent/>
          {children}
          <Footer/>
        </Providers>
      </body>
>>>>>>> 0267a0a04f0d654ee9a4234823d205c90bde2816
    </html>
  );
}
